services:
  xterra_ros:
    build:
      context: .
      dockerfile: Dockerfile
    image: xterra_autonomy_beta
    container_name: xterra_autonomy_container
    runtime: nvidia
    privileged: true
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    devices:
      - /dev/input:/dev/input
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri:/dev/dri
      - /dev:/dev
      - /dev/hidraw0:/dev/hidraw0 # ADD THIS
      - /dev/hidraw1:/dev/hidraw1 # ADD THIS
    device_cgroup_rules:
      - "c 81:* rmw"
      - "c 189:* rmw"
      - "c 510:* rmw" # ADD THIS - hidraw major number
    group_add:
      - video
      - dialout
      - plugdev # ADD THIS - hidraw group
    command: bash
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/argus_socket:/tmp/argus_socket:rw
      - ${HOME}/.Xauthority:/home/ros/.Xauthority:rw
      - .:/home/ros2_ws
      - ${HOME}/.gazebo:/home/ros/.gazebo
      - ${HOME}/.rviz:/home/ros/.rviz
      - /dev/shm:/dev/shm
      - /sys:/sys:rw
      - /sys/bus/usb:/sys/bus/usb:rw
      - /run/udev:/run/udev:rw
      - /dev/bus/usb:/dev/bus/usb:rw
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - CMAKE_PREFIX_PATH=/opt/OrbbecSDK_v2.4.11/lib:$CMAKE_PREFIX_PATH
      - ROS_DOMAIN_ID=0
    stdin_open: true
    tty: true
