go2:
  tau_limit: 
    tau1: 23.7
    tau2: 23.7
    tau3: 45.43
  base_link: "trunk"
  sleep_pose:
    q1: 0.0
    q2: 0.9
    q3: 0.0
    q4: 0.0
    q5: 0.9
    q6: 0.0
    q7: 0.0
    q8: 0.65
    q9: 0.0
    q10: 0.0
    q11: 0.65
    q12: 0.0
  entity: "go2"
  
m2:
  tau_limit: 
    tau1: 10.0
    tau2: 10.0
    tau3: 20.0
  base_link: "base_link"
  sleep_pose:
    q1: 0.0
    q2: 0.7
    q3: -1.4
    q4: 0.0
    q5: 0.7
    q6: -1.4
    q7: 0.0
    q8: 0.7
    q9: -1.4
    q10: 0.0
    q11: 0.7
    q12: -1.4
  entity: "svan"

m2_metal:
  tau_limit: 
    tau1: 20.0
    tau2: 20.0
    tau3: 55.0
  base_link: "base_link"
  sleep_pose:
    q1: 0.0
    q2: 0.7
    q3: -1.4
    q4: 0.0
    q5: 0.7
    q6: -1.4
    q7: 0.0
    q8: 0.7
    q9: -1.4
    q10: 0.0
    q11: 0.7
    q12: -1.4
  entity: "m2_metal"


aliengo:
  tau_limit: 
    tau1: 35.278
    tau2: 35.278
    tau3: 44.4
  base_link: "trunk"
  sleep_pose:
    q1: 0.0
    q2: 0.9
    q3: -1.75
    q4: 0.0
    q5: 0.9
    q6: -1.75
    q7: 0.0
    q8: 0.9
    q9: -1.75
    q10: 0.0
    q11: 0.9
    q12: -1.75
  entity: "aliengo"
    