robot_name: go2
base:
  name: base_link
  geoms:
    mesh: "package://go2_description/meshes/base.STL"
    box: {size: "0.3762 0.0935 0.114"}
    cylinder: {radius: "0.1", length: "0.3"}
  pos: "0 0 0.5"
  quat: "1 0 0 0"
  inertial:
    origin: {xyz: "0 0 0", rpy: "0 0 0"}
    mass: 6.921
    inertia: {ixx: 0.02448, ixy: 0.00012166, ixz: 0.0014849, iyy: 0.098077, iyz: 0.0, izz: 0.107}
  visual:
    origin: {xyz: "0 0 0", rpy: "0 0 0"}
    geometry: {type: mesh}
    material: {name: "gray"}
  collision:
    origin: {xyz: "0 0 0", rpy: "0 0 0"}
    use_mesh: false
    geometry: {type: 'box'}
imu: 
  name: imu_link
  joint_name: base_to_imu
  origin: {xyz: "0 0 0", rpy: "0 0 0"}
limbs:
  - prefix: FL
    attach_to: base_link
    chain:
      - suffix: hip
        geoms:
          mesh: "package://go2_description/dae/hip.dae"
          cylinder: {length: "0.04", radius: "0.046"}
        link:
          suffix: link
          inertial:
            origin: {xyz: "0 0 0", rpy: "0 0 0"}
            mass: 1.0
            inertia: {ixx: 0.01, ixy: 0, ixz: 0, iyy: 0.01, iyz: 0, izz: 0.01}
          visual:
            origin: {xyz: "0 0 0", rpy: "0 0 0"}
            geometry: {type: mesh}
            material: {name: "gray"}
          collision:
            origin: {xyz: "0 0 0", rpy: "0 0 0"}
            geometry: {type: cylinder}
        joint:
          suffix: joint
          type: revolute
          origin: {xyz: "0.25 0.25 0", rpy: "0 0 0"}
          axis: {xyz: "1 0 0"}
          limit: {lower: -1.04, upper: 1.04, effort: 23.7, velocity: 30}
      - suffix: thigh
        geoms:
          mesh: "package://go2_description/dae/thigh.dae"
          box: {size: "0.213 0.0245 0.034"}
        link:
          suffix: link
          inertial:
            origin: {xyz: "0 0 -0.1", rpy: "0 0 0"}
            mass: 2.0
            inertia: {ixx: 0.01, ixy: 0, ixz: 0, iyy: 0.01, iyz: 0, izz: 0.01}
          visual:
            origin: {xyz: "0 0 0", rpy: "0 0 0"}
            geometry: {type: mesh}
            material: {name: "gray"}
          collision:
            origin: {xyz: "0 0 0", rpy: "0 0 0"}
            geometry: {type: box}
        joint:
          suffix: joint
          type: revolute
          origin: {xyz: "0 0.05 0", rpy: "0 0 0"}
          axis: {xyz: "0 1 0"}
          limit: {lower: -1.5236, upper: 3.4907, effort: 23.7, velocity: 30}
      - suffix: calf
        geoms:
          mesh: "package://go2_description/dae/calf.dae"
          cylinder: {radius: "0.012", length: "0.12"}
        link:
          suffix: link
          inertial:
            origin: {xyz: "0 0 -0.15", rpy: "0 0 0"}
            mass: 2.0
            inertia: {ixx: 0.01, ixy: 0, ixz: 0, iyy: 0.01, iyz: 0, izz: 0.01}
          visual:
            origin: {xyz: "0 0 0", rpy: "0 0 0"}
            geometry: {type: mesh}
            material: {name: "gray"}
          collision:
            origin: {xyz: "0 0 0", rpy: "0 0 0"}
            geometry: {type: cylinder}
        joint:
          suffix: joint
          type: revolute
          origin: {xyz: "0 0 -0.3", rpy: "0 0 0"}
          axis: {xyz: "0 1 0"}
          limit: {lower: -2.7227, upper: -0.83776, effort: 45.43, velocity: 10}
      - suffix: foot
        geoms:
          mesh: "package://go2_description/dae/foot.dae"
          sphere: {radius: 0.02}
        link:
          suffix: ""
          inertial:
            origin: {xyz: "0 0 -0.02", rpy: "0 0 0"}
            mass: 0.2
            inertia: {ixx: 0.01, ixy: 0, ixz: 0, iyy: 0.01, iyz: 0, izz: 0.01}
          visual:
            origin: {xyz: "0 0 0", rpy: "0 0 0"}
            geometry: {type: mesh}
            material: {name: "gray"}
          collision:
            origin: {xyz: "0 0 0", rpy: "0 0 0"}
            geometry: {type: sphere}
        joint:
          suffix: "joint"
          type: "fixed"
          origin: {xyz: "0 0 -0.02", rpy: "0 0 0"}
          axis: {xyz: "0 0 0"}
          limit: {lower: 0, upper: 0, effort: 1000, velocity: 0}
# For MJCF-specific
options:
  timestep: 0.002
  gravity: "0 0 -9.81"
