cameras:  
    front_cam:
      fps: 15
      resolution: [ 424, 240 ]
      camera_name: "head_cam"
      user_defined_cam_id: "head_orbbec_1"
      cam_serial_number: "CP1564100075"
      camera_topics: [ "/sensors/front_rgbd_cam_color/image_raw", "/sensors/front_rgbd_cam_depth/depth/image_raw" ]
      stream_types: [ "false", "false", "false", "false"]    

    right_cam:
      fps: 6
      resolution: [ 424, 240 ]
      camera_name: "arm_cam"
      user_defined_cam_id: "arm_orbbec_2"
      cam_serial_number: "CP15641000C5"
      camera_topics: [ "/sensors/right_rgbd_cam_color/image_raw", "/sensors/right_rgbd_cam_depth/depth/image_raw" ]
      stream_types: [ "true", "false", "false", "false"]

    # left_cam:
    #   fps: 30
    #   resolution: [ 424, 240 ]
    #   camera_name: "intel_camera"
    #   user_defined_cam_id: "cam_02"
    #   cam_serial_number: "242322077676"
    #   camera_topics: [ "/sensors/left_rgbd_cam_color/image_raw", "/sensors/left_rgbd_cam_depth/depth/image_raw" ]

    # back_cam:
    #   fps: 30
    #   resolution: [ 424, 240 ]
    #   camera_name: "back_rgbd_cam"
    #   user_defined_cam_id: "cam_03"
    #   cam_serial_number: "CP0E853000FK"
    #   camera_topics: [ "/sensors/back_rgbd_cam_color/image_raw", "/sensors/back_rgbd_cam_depth/depth/image_raw" ]

   

